# Generated by Django 5.1.3 on 2024-11-28 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_like', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica4.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica4.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'post')},
            },
        ),
    ]
